Default: &defaults
  database: filehost-hs.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: filehost-hs_test.sqlite3
  <<: *defaults

Staging:
  database: filehost-hs_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: filehost-hs_production.sqlite3
  poolsize: 100
  <<: *defaults
